# Generated by Django 4.0.4 on 2022-05-15 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('detectionProbability', models.FloatField()),
                ('detectionCoordinates', models.JSONField()),
                ('commentary', models.TextField()),
                ('isSent', models.SmallIntegerField()),
                ('videoName', models.TextField()),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('shiftId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('filmingTime', models.JSONField()),
                ('videos', models.JSONField()),
                ('motion', models.JSONField()),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Choise_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('restaurants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.restaurants')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.shift')),
            ],
        ),
    ]
