# Generated by Django 4.0.4 on 2022-05-15 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_restoran'),
        ('polls', '0004_choise_video_restaurants_remove_person_city_and_more'),
    ]

    operations = [
    ]
